/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package_view.dialog;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import package_model.Model_Q6_1_8;
import static package_view.Activity_List.list_show_q678;
import static package_view.Activity_List.mode;
import static package_view.Activity_List.q_rank;
import static package_view.Main_.Question_index_indicator;

/**
 *
 * @author Miz
 */
public class Dialog_box_Q6_1_Q8 extends javax.swing.JDialog {

    public static List<Model_Q6_1_8> list_of_description_for_question_six_one;
    public static List<Model_Q6_1_8> list_of_description_for_question_seven;
    public static List<Model_Q6_1_8> list_of_description_for_question_eghit;

    String q_txt_area_description;

    String Header_Based_on_Number[] = {"", "Task Performed", "Room cleanness", "Telephone Line"};

    /**
     * Creates new form Dialog_box_Q6_1_Q8
     *
     * @param parent
     * @param modal
     */
    public Dialog_box_Q6_1_Q8(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        /* if question indicator indicate for question number six one and object of the list_description for question six one is not null */
        if ((list_of_description_for_question_six_one != null) && (Question_index_indicator == 61)) {
            lbl_Q61_Q8_dialog_header.setText(Header_Based_on_Number[1]);

            q_txt_area_description = list_of_description_for_question_six_one.get(0).getDescription();
            txt_area_description_q_6_1_8.setText(q_txt_area_description);

        } else if ((list_of_description_for_question_six_one == null) && (Question_index_indicator == 61)) {
            lbl_Q61_Q8_dialog_header.setText(Header_Based_on_Number[1]);
        }/*end of else if for question six one */                
        
        /*Q7*/
        
        if ((list_of_description_for_question_seven != null) && (Question_index_indicator == 7)) {
            lbl_Q61_Q8_dialog_header.setText(Header_Based_on_Number[2]);

            q_txt_area_description = list_of_description_for_question_seven.get(0).getDescription();
            txt_area_description_q_6_1_8.setText(q_txt_area_description);

        } else if ((list_of_description_for_question_seven == null) && (Question_index_indicator == 7)) {
            lbl_Q61_Q8_dialog_header.setText(Header_Based_on_Number[2]);
        }
        
        
        /*Q8*/
        
        if ((list_of_description_for_question_eghit != null) && (Question_index_indicator == 8)) {
            lbl_Q61_Q8_dialog_header.setText(Header_Based_on_Number[3]);

            q_txt_area_description = list_of_description_for_question_eghit.get(0).getDescription();
            txt_area_description_q_6_1_8.setText(q_txt_area_description);

        } else if ((list_of_description_for_question_eghit == null) && (Question_index_indicator == 8)) {
            lbl_Q61_Q8_dialog_header.setText(Header_Based_on_Number[3]);
        }
        
         if(mode.equals("show_q61")){
             switch(q_rank){
                 case 61:
                     lbl_Q61_Q8_dialog_header.setText(Header_Based_on_Number[1]);
                     txt_area_description_q_6_1_8.setText(list_show_q678.get(0).getDes6());
                     //System.out.println("data and header No 61" + list_show_q678.get(0).getDes6() + " " + Header_Based_on_Number[1]);
                     break;
                 case 7:
                     lbl_Q61_Q8_dialog_header.setText(Header_Based_on_Number[2]);
                     txt_area_description_q_6_1_8.setText(list_show_q678.get(0).getDes7());                     
                     //System.out.println("data and header No 7" + list_show_q678.get(0).getDes7() + " " + Header_Based_on_Number[2]);
                     break;
                 case 8:
                     lbl_Q61_Q8_dialog_header.setText(Header_Based_on_Number[3]);
                     txt_area_description_q_6_1_8.setText(list_show_q678.get(0).getDes8());
                     //System.out.println("data and header No 8" + list_show_q678.get(0).getDes8() + " " + Header_Based_on_Number[3]);
                     break;
             }
             btn_save.setVisible(false);
         }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Q61_Q8_dialog_header = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area_description_q_6_1_8 = new javax.swing.JTextArea();
        btn_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(32, 31, 95));

        lbl_Q61_Q8_dialog_header.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        lbl_Q61_Q8_dialog_header.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Q61_Q8_dialog_header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Q61_Q8_dialog_header.setText("Task Performed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Q61_Q8_dialog_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Q61_Q8_dialog_header, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jLabel2.setText("Description :");

        txt_area_description_q_6_1_8.setColumns(20);
        txt_area_description_q_6_1_8.setRows(5);
        jScrollPane1.setViewportView(txt_area_description_q_6_1_8);

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/package_res/add_new.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_save))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_save)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if(txt_area_description_q_6_1_8.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Fill the Input Field","Error!", JOptionPane.ERROR_MESSAGE);            
            return;
        }
        q_txt_area_description = txt_area_description_q_6_1_8.getText();
        Model_Q6_1_8 model = new Model_Q6_1_8(q_txt_area_description);
        switch (Question_index_indicator) {
            case 61:
                list_of_description_for_question_six_one = new ArrayList<>();
                if (list_of_description_for_question_six_one.size() > 0) {
                    list_of_description_for_question_six_one.removeAll(list_of_description_for_question_six_one);
                }
                list_of_description_for_question_six_one.add(model);
                break;
            case 7:
                list_of_description_for_question_seven = new ArrayList<>();
                if(list_of_description_for_question_seven.size() > 0){
                    list_of_description_for_question_seven.removeAll(list_of_description_for_question_seven);
                }
                list_of_description_for_question_seven.add(model);
                break;
            case 8:
                list_of_description_for_question_eghit = new ArrayList<>();
                if(list_of_description_for_question_eghit.size() > 0){
                    list_of_description_for_question_eghit.removeAll(list_of_description_for_question_eghit);                    
                }
                list_of_description_for_question_eghit.add(model);

        }

        this.dispose();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        switch(Question_index_indicator){
            case 61:
                if(list_of_description_for_question_six_one != null){
                    list_of_description_for_question_six_one.removeAll(list_of_description_for_question_six_one);
                    list_of_description_for_question_six_one = null;
                }
                break;
            case 7:
                if(list_of_description_for_question_seven != null){
                    list_of_description_for_question_seven.removeAll(list_of_description_for_question_seven);
                    list_of_description_for_question_seven = null;
                }
                break;
            case 8:
                if(list_of_description_for_question_eghit != null){
                    list_of_description_for_question_eghit.removeAll(list_of_description_for_question_eghit);
                    list_of_description_for_question_eghit = null;
                }
        }
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Q61_Q8_dialog_header;
    private javax.swing.JTextArea txt_area_description_q_6_1_8;
    // End of variables declaration//GEN-END:variables
}
